#!/system/bin/sh
# Magic Charging Switch (mcs)
# (c) 2017-2018, VR25 @ xda-developers
# License: GPL v3+



modID=mcs
modData=/data/media/$modID
PATH=/sbin/.core/busybox:/dev/magisk/bin
config=$modData/config.txt
system=/system
[[ -d /system_root ]] && system=/system_root/system 



# verbosity engine
logsDir=$modData/logs
newLog=$logsDir/${modID}_verbose_log.txt
oldLog=$logsDir/${modID}_verbose_previous_log.txt
[[ -d $logsDir ]] || mkdir -p $logsDir
if [[ $1 != debug ]]; then
  [[ -f $newLog ]] && mv $newLog $oldLog
  set -x 2>>$newLog
fi



get_prop() {
	FILE="$2"
	[ -z "$FILE" ] && FILE="$config"
	sed -n "s|^$1=||p" "$FILE" 2>/dev/null
}

set_prop() { sed -i "s|^$1=.*|$1=$2|g" "$config"; }



# find modPath
echo
modPath=/sbin/.core/img/$modID
[[ -f $modPath/module.prop ]] || modPath=/magisk/$modID
[[ -f $modPath/module.prop ]] || \
  { echo -e "(!) modPath not found\n"; exit 1; }
defaultConfig=$modPath/config/${modID}
modVersion="$(get_prop versionCode $modPath/module.prop)"



# device ID
for i in ro.product.device ro.build.product; do
	model="$(get_prop $i $system/build.prop)"
	[ -n "$model" ] && break || model=generic
done
device="$(get_prop ro.product.brand $system/build.prop)_$model"



debug() {
	set +x
	echo "(i) Gathering debugging data..."
	rm $logsDir/${modID}_debug*txt 2>/dev/null
	rm /sdcard/${modID}_debug*txt 2>/dev/null
	
	exec 3>&1
	exec >$logsDir/${modID}_debug_log-${device}-${modVersion}-$(date +%Y%m%d%H%M%S).txt
	echo -e "$(date)\n${modID}Version=$modVersion\n\n\n"
 
	echo -e "### PROPS ###\n"
  $system/bin/getprop | grep -Ei 'product|version'
  echo -e "\n\n"

	echo -e "### /sys/class/power_supply/* ###\n"
	generate_sys_cache
	cat $modData/sys_cache
	echo -e "\n"
  
	echo -e "### POWER UEVENT ###\n"
	generate_sys_cache null_value
	for ueventFile in $(grep -i 'battery/uevent' $modData/sys_cache); do
		chmod +r "$ueventFile"
		if grep -i '^POWER_SUPPLY_NAME=' "$ueventFile" | grep -Eiq 'battery$|smb.*\-battery$'; then
			echo "[$ueventFile]"
			cat "$ueventFile"
			echo
		fi
	done
	echo -e "\n"
	
	for file in $modData/* $modData/logs/*; do
		if [[ -f $file ]] && ! echo "$file" | grep -Eq 'sys_cache|_debug_log'; then
			echo -e "### $file ###\n"
			cat "$file"
			echo -e "\n\n"
		fi
	done
	
	exec 1>&3 3>&-

  cp -f $logsDir/${modID}_debug*txt /sdcard/
	echo -e "\n-- Generated file: $( ls /sdcard/${modID}_debug*txt)\n"
	echo -e "-- Support thread: https://forum.xda-developers.com/apps/magisk/module-magic-charging-switch-cs-v2017-9-t3668427\n"
	rm $modData/sys_cache
	exit 0
}



# charging loop
c_loop() {
	$(get_prop loopVerbose) || set +x
	Switch ON
	while :; do
		until [ "$(batt_level)" -ge "$1" ]; do
			clear
			echo "Charging until $1%..."
			echo "Current battery level: $(batt_level)%"
			echo -e "$startTime\n"
			echo "(i) Press CTRL (Vol. Down) + C to abort."
			sleep 12
		done

		Switch OFF
		echo -e "\n(i) Desired charge % reached."
		end_time
		
		# Reset battery stats
		dumpsys batterystats --reset &>/dev/null
		
		echo -e "- Charging paused.\n"
		echo "(i) Waiting until $(lower_limit)% to restart the cycle..."
		echo "- Press CTRL (Vol. Down) + C to abort."
		
		until [ "$(batt_level)" -le "$(lower_limit)" ]; do
			sleep 12
		done
		
		Switch ON
	done
	exit 0
}



check_compatibility() {
	echo "(i) Checking compatibility..."

	# preparation
	generate_sys_cache null_value


	# test 1 -- uevent
	for ueventFile in $(grep -i 'battery/uevent' $modData/sys_cache); do
		chmod +r "$ueventFile"
		if grep -i '^POWER_SUPPLY_NAME=' "$ueventFile" | grep -Eiq 'battery$|smb.*\-battery$'; then
			set_prop uevent "$ueventFile"
			break
		fi
	done


	# test 2 -- charging switch
	if [[ -f $(uevent) ]]; then

		if ! charging; then
			echo "- Waiting for charger..."
			$(get_prop loopVerbose) || set +x
			until charging; do sleep 5; done
			$(get_prop loopVerbose) || set -x 2>>$newLog
			echo "-- Charger detected"
			echo "- Please wait..."
		fi
		
		for ctrlFile in $(grep -Ev '#|^$' $modPath/config/switches); do
			for ctrlFile_ in $(grep "$ctrlFile" $modData/sys_cache); do
				if [[ -f "$ctrlFile_" ]]; then
					chmod +r "$ctrlFile_"
					set_switch "$ctrlFile_"
					[ "$?" = "3" ] && continue
					if [ -n "$(get_prop offKey)" ]; then
						Switch OFF
						sleep 2
						charging || break
					fi
				fi
			done
			if ! charging; then
				Switch ON
				sleep 2
				charging && break || set_switch
			else
				[ -n "$(get_prop onKey)" ] && Switch ON
				set_switch
			fi
		done
	fi


	# verdict
	if [[ ! -f $(Switch) ]]; then
		echo -e "- (!) Incompatible device.\n-- Your kernel may not support advanced charging control.\n"
		debug
	else
		echo -e "- Congratulations, your device is supported!\n"
		rm $modData/sys_cache
		sleep 2
	fi
}


exit1() {
  echo "(!) $*: Invalid option(s)/argument(s)"
  echo -e "- Run \"${modID} -h\" for help\n"
  exit 1
}


set_switch() {
	if [ -n "$1" ]; then
		set_prop switch "$1"
		case $(cat "$(Switch)") in
			1) set_prop onKey 1; set_prop offKey 0;;
			0) set_prop onKey 0; set_prop offKey 1;;
			on) set_prop onKey on; set_prop offKey off;;
			off) set_prop onKey off; set_prop offKey on;;
			100) set_prop onKey 100; set_prop offKey 3;;
			true) set_prop onKey true; set_prop offKey false;;
			false) set_prop onKey false; set_prop offKey true;;
			enable) set_prop onKey enable; set_prop offKey disable;;
			disable) set_prop onKey disable; set_prop offKey enable;;
			enabled) set_prop onKey enabled; set_prop offKey disabled;;
			disabled) set_prop onKey disabled; set_prop offKey enabled;;
			Charging) set_prop onKey Charging; set_prop offKey Discharging;;
			*) return 3;;
		esac 2>/dev/null
	else
		# reset values back to null
		set_prop switch
		set_prop onKey
		set_prop offKey
	fi
}


Switch() {
	if [ -z "$1" ]; then
		get_prop switch
	else
		chmod +rw "$(Switch)"
		case $1 in
			ON) echo "$(get_prop onKey)" >"$(Switch)";;
			OFF) echo "$(get_prop offKey)" >"$(Switch)";;
		esac
	fi
}


OFF_time() {
	if $invertOff; then Switch ON; else Switch OFF; fi
	if [ -n "$1" ]; then
		if echo "$1" | grep -q '[a-z]'; then
		
			if $invertOff; then
				echo "(i) Charging enabled for $1."
			else
				echo "(i) Charging disabled for $1."
			fi
			start_time
			
			if echo "$1" | grep -q 'm'; then
				sleep $(( 60 * $(echo $1 | sed 's/m//') ))
			elif echo "$1" | grep -q 'h'; then
				sleep $(( 3600 * $(echo $1 | sed 's/h//') ))
			else exit1
			fi
		elif ! echo "$1" | grep -q '[a-z]' \
			&& echo "$1" | grep -q '[0-9]'; then
			
			if $invertOff; then
				echo "(i) Charging enabled for $1s."
			else
				echo "(i) Charging disabled for $1s."
			fi
			start_time
			sleep $1
		fi
		echo -e "\n(i) Timeout reached."
		
		if $invertOff; then
			Switch OFF
			echo "- Charging disabled."
		else
			Switch ON
			echo "- Charging re-enabled"
		fi
		end_time

	else
		if $invertOff; then
			echo "(i) Charging enabled."
		else
			echo "(i) Charging disabled."
		fi
	fi
	echo
}


OFF_percent() {
	if $invertOff; then
		Switch ON
		echo "(i) Charging enabled until $1."
	else
		Switch OFF
		echo "(i) Charging disabled until $1."
	fi
	start_time

	echo
	until [ "$(batt_level)" -ge "$(echo $1 | sed 's/%//')" ]; do
		sleep 12
	done
	echo "(i) Desired % reached."
		
	if $invertOff; then
		Switch OFF
		echo "- Charging disabled."
	else
		Switch ON
		echo "- Charging re-enabled"
	fi
	end_time
	echo
}


auto_run() { get_prop autoRun; }

batt_level() { get_prop POWER_SUPPLY_CAPACITY "$(uevent)"; }

charging() { grep -iqs '=charging$' "$(uevent)"; }

end_time() { echo "- End time: $(date)"; }

higher_limit() { get_prop higherLimit; }

lower_limit() { get_prop lowerLimit; }

pause_daemon() { get_prop pauseDaemon; }

start_time() { echo "- Start time: $(date)"; }

uevent() { get_prop uevent; }


update_cfg() {
	if [ -z "$1" ]; then
		set_prop higherLimit 90
		set_prop lowerLimit 80
	else
		if [ -n "$2" ]; then
			set_prop higherLimit "$1"
			set_prop lowerLimit "$2"
		else 
			set_prop higherLimit "$1"
			set_prop lowerLimit 80
		fi
	fi
}


generate_sys_cache() {
	for e in /sys/class/power_supply/*; do
		for file in $(find "$(readlink -f "$e")" -type f 2>/dev/null); do
			chmod +r "$file"
			if [ "$1" = "null_value" ]; then
				echo "$file"
			else
				echo "$file [$(cat "$file" 2>/dev/null | head -n1)]"
			fi
		done
		echo
	done >$modData/sys_cache
}


# self-check
if ! echo "$1 $2" | grep -Eq '\-x|\-h|\-r|debug' &>/dev/null; then
	if [[ ! -f $(Switch) || ! -f $config ]]; then
		cp $defaultConfig $config
		check_compatibility
	fi
	if ! $(auto_run) || $(pause_daemon); then
		startTime="$(start_time)"
	fi
	invertOff=false
fi



# options menu
case $1 in

	# manually set a charging switch
	-x)
		echo "(i) Please wait..."
		generate_sys_cache null_value
		for ueventFile in $(grep -i 'battery/uevent' $modData/sys_cache); do
			chmod +r "$ueventFile"
			if grep -i '^POWER_SUPPLY_NAME=' "$ueventFile" | grep -Eiq 'battery$|smb.*\-battery$'; then
				set_prop uevent "$ueventFile"
				break
			fi
		done

		if [[ ! -f $(uevent) ]]; then
			echo -e "(!) Unsupported device\n"
			debug
		fi
		
		if [ -n "$2" ]; then
			set_switch "$2"
			if [ -n "$4" ]; then
				set_prop onKey $3
				set_prop offKey $4
			fi
			echo -e "- Charging switch set successfully.\n"
		
		else
			echo "- Fetching known control files for ${device}..."
			: >$modData/.${modID}x
			count=0

			if ! charging; then
				echo "-- Waiting for charger..."
				until charging; do sleep 5; done
				echo "--- Charger detected"
				echo "-- Please wait..."
			fi

			echo
			[[ -f $(Switch) ]] || set_switch dummy_switch

			for ctrlFile in $(grep -Ev '#|^$' $modPath/config/switches); do
				for ctrlFile_ in $(grep "$ctrlFile" $modData/sys_cache | grep -v "$(Switch)"); do
					if [[ -f $ctrlFile_ ]]; then
						((count++))
						echo -e "[$count] $ctrlFile_\n" >>$modData/.${modID}x
					fi
				done
			done

			if grep -q '[a-z]' $modData/.${modID}x; then
				cat $modData/.${modID}x
				echo "(i) Pick a number..."
				read Input
				if [ -n "$Input" ]; then
					set_switch "$(grep "\[${Input}\] " $modData/.${modID}x | awk '{print $2}')"
					echo -e "\n(i) New switch set successfully.\n"
				fi
			else
				echo -e "\n(i) No additional switch(es) found\n"
			fi

		fi
		rm $modData/.${modID}x $modData/sys_cache 2>/dev/null
		[[ -f $(Switch) ]] || set_switch
		exit 0
		;;


	debug) debug;;


	# toggle daemon state
	-s)
		if [ "$2" = "stop" ]; then
			set_prop autoRun false
			set_prop pauseDaemon false
			echo "(i) ${modID} daemon stopped."
		elif [ "$2" = "start" ]; then
			set_prop autoRun true
			set_prop pauseDaemon false
      (${modID} daemon) &
			echo "(i) ${modID} daemon started."
		else
			if $(pause_daemon); then
				set_prop pauseDaemon false
				Switch ON
				echo "(i) ${modID} daemon resumed."
			else
				set_prop pauseDaemon true
				echo "(i) ${modID} daemon paused."
			fi
		fi
		echo
		;;


	# toggle extensive (loops) verbose
  # don't let this be enabled forever
		-v)
		if $(get_prop loopVerbose); then
			set_prop loopVerbose false
			echo -e "(i) Loop verbose disabled"
		else
			set_prop loopVerbose true
			echo -e "(i) Loop verbose enabled"
		fi
		echo
		exit 0
		;;


	# keep/maintain battery power at a constant level
  # $2=%value
	-k)
		$(get_prop loopVerbose) || set +x
		if $(auto_run) && ! $(pause_daemon); then
			set_prop pauseDaemon true
			echo "(i) ${modID} daemon paused."
			echo -e "- Reboot or run \"${modID} -s\" to resume.\n"
		fi
		
		echo "Maintaining $2%..."
		echo "(i) Press CTRL (Vol. Down) + C to abort."
		Switch ON

		while :; do

			until [ "$(batt_level)" -ge "$2" ] || ! charging; do
				sleep 12
			done

			[ "$(batt_level)" -ge "$2" ] && Switch OFF
		
			until [ "$(batt_level)" -le "$2" ] || charging; do
				sleep 12
			done

			[ "$(batt_level)" -le "$2" ] && Switch ON

		done
		exit 0
		;;


	# reset battery stats on demand
	-b)
		dumpsys batterystats --reset
		echo
		exit 0
		;;
	


	# reset settings
	-r)
		cp $defaultConfig $config \
			&& { echo -e "(i) Settings reset successfully.\n"; exit 0; } \
			|| { echo -e "(!) Settings reset failed.\n"; exit 1; }
		;;



	# daemon
	daemon)
		$(get_prop loopVerbose) || set +x
		if $(auto_run); then
			set_prop pauseDaemon false
			Switch ON
		else
			exit 0
		fi
		while $(auto_run); do
			$(pause_daemon) && sleep 12
			until $(pause_daemon); do
				if [ "$(batt_level)" -le "$(lower_limit)" ] \
				&& [ "$(get_prop offKey)" = "$(cat "$(Switch)")" ]; then
					Switch ON
				fi
				sleep 12
				if [ "$(batt_level)" -ge "$(higher_limit)" ] \
				&& [ "$(get_prop onKey)" = "$(cat "$(Switch)")" ]; then
					Switch OFF
					dumpsys batterystats --reset &>/dev/null
				fi
				sleep 12
			done
		done
		exit 0
		;;



	# help
	--help|-h|help)
		set +x
		cat <<EOD
Magic Charging Switch (mcs)

Advanced battery charging controller


Usage:

mcs [-b] [-h] [-i] [-r] [-v] [debug] [-k %LEVEL] [%PAUSE %RESUME] [%PAUSE] [-m/t %PAUSE %RESUME] [-s start/stop] [-d/e %/TIMEOUT] [-x /path/to/switch onValue offValue]

-b --> reset battery stats on demand (does not work on all devices)

-i --> display power info

-r --> reset settings

-s --> pause/resume, start/stop daemon

-v --> toggle extensive (loops) verbose

-x --> pick a charging switch from the database

debug --> gather debugging data & save it to $logsDir/mcs_debug_log-\$device-\$csVER-\$date.txt

-k %LEVEL --> keep/maintain battery power at a constant %LEVEL (pauses mcs daemon)

[no args] --> run with default/previous settings

-h/--help/help --> help

%PAUSE %RESUME --> pause charging at %PAUSE value (default 90); resume if battery drops below %RESUME (default 80). This is the INITIAL SETUP COMMAND. If auto-run is OFF, the command works as is; else, new settings are saved and automatically picked up by mcs daemon.

-m/-t %PAUSE %RESUME --> generate automation config (-m for MacroDroid; -t for Tasker -- pick one)

-d/e [%/TIMEOUT (optional)] --> disable/enable charging on demand (pauses mcs daemon)

-x /path/to/switch onValue offValue -- > manually set a charging switch; if values match one of the following groups, as is or in reverse order -- you don't have to specify them: 1/0, enable/disable, enabled/disabled, true/false, on/off, 100/3, Charging/Discharging


Usage Examples/Tips

"mcs 90" --> pause charging at 90%; resume when battery level is less or equal to 80% (default).

"mcs 80 20" --> pause charging at 80%; resume when battery level is less or equal to 20%.

"mcs -d" --> disable charging.

"mcs -d" --> enable charging. 

"mcs -d 30m" --> keep charging disabled for 30 minutes.

"mcs -e 1h" --> keep charging enabled for 1 hour. 

"mcs -e 80%" --> Charge until battery level equals 80%.

"mcs -d 40%" --> Charge until battery level equals 40%.

"mcs -e 120 && mcs -d 30m && mcs -e 1h" --> charge for 120 seconds, pause for 30 minutes, then charge again for 1h.

"mcs -e 30m && mcs -d 30m && mcs -e 90%" --> charge for 30 minutes, pause for 30 minutes, then charge again, but this time until battery level is greater or equal to 90%.

"mcs -e 50% && mcs -d 5h && mcs -e 80% && mcs -d 30m && mcs -e 90%" --> charge until 50%, pause for 5 hours, charge until 80%, pause for 30 minutes, charge until 90%.

Ideally, you want your battery level between 40-60% - best, 20-80% - average, 10-90% - fair.

For best convenience, stick with mcs 90 80; mcs 80 70 for a perfect balance between convenience & battery wear. If you want the longest battery lifespan, use mcs 42 41 or mcs -k 42 (best for prolonged usage -- i.e., navigation).
EOD
	echo
	exit 0
	;;


	# disable charging on demand
    # $2=#% or timeout
	-d)
		if $(auto_run) && ! $(pause_daemon); then
			set_prop pauseDaemon true
			echo -e "(i) ${modID} daemon paused.\n"
		fi
		
		if [ -n "$2" ]; then
			case $2 in
				*[0-9]%) OFF_percent $2;;
				*) OFF_time $2;;
			esac
		else OFF_time; fi

		if $(auto_run) && $(pause_daemon); then
			echo -e "(i) Reboot or run \"${modID} -s\" to resume ${modID} daemon.\n"
		fi
		exit 0
		;;


	# enable charging on demand
  # $2=#% or timeout
	-e)
		if $(auto_run) && ! $(pause_daemon); then
			set_prop pauseDaemon true
			echo "(i) ${modID} daemon paused.\n"
		fi
		
		invertOff=true
		if [ -n "$2" ]; then
			case $2 in
				*[0-9]%) OFF_percent $2;;
				*) OFF_time $2;;
			esac
		else OFF_time; fi
		
		if $(auto_run) && $(pause_daemon); then
			echo -e "(i) Reboot or run \"${modID} -s\" to resume ${modID} daemon.\n"
		fi
		exit 0
		;;


	# battery & settings info
	-i)
		echo -e "POWER INFO\n"
		cat "$(uevent)"
    echo
    echo
		cat $config | sed 's/# //'
		echo
		exit 0
		;;


	# run with previous settings
  # or apply default charging limits (higherLimit=90 lowerLimit=80)
	"")
		if $(auto_run) && ! $(pause_daemon); then
			echo -e "(i) ${modID} daemon is already running.\n"
			exit 0
		fi

		c_loop $(higher_limit)
		;;


	# generate MacroDroid & Tasker automation configs
	-m|-t)
		case $1 in
			-m)
				echo "(i) Generating /sdcard/MacroDroid/${modID}.category..."
				mDir=/sdcard/MacroDroid
				[[ -d $mDir ]] || mkdir $mDir
				cp $modPath/config/macrodroid $mDir/${modID}.category
				cd $mDir
				sed -i "s/:90/:$2/; s/:11/:$3/" ${modID}.category
				;;

			-t)
				echo "(i) Generating /sdcard/Tasker/projects/${modID}.prj.xml..."
				tDir=/sdcard/Tasker/projects
				[[ -d $tDir ]] || mkdir -p $tDir
				cp $modPath/config/tasker $tDir/${modID}.prj.xml
				cd $tDir
				sed -i "/<Int sr=\"arg0\" val=\"90\"\/>/s/90/$2/" ${modID}.prj.xml
				sed -i "/<rhs>90<\/rhs>/s/90/$2/" ${modID}.prj.xml
				sed -i "/<Int sr=\"arg1\" val=\"10\"\/>/s/10/$3/" ${modID}.prj.xml
				sed -i "/<rhs>10<\/rhs>/s/10/$3/" ${modID}.prj.xml
				;;

			*) exit1;;
		esac

		echo -e "- End\n"
		exit 0
		;;


	# initial setup
  # $1=higherLimit (i.e., 90)
  # $2=lowerLimit (i.e., 80)
	[0-9]*)
		update_cfg $1 $2
		echo "(i) New settings saved."
		sleep 1

		if $(auto_run) && ! $(pause_daemon); then
			echo "- ${modID} daemon is already running."
			echo -e "-- Now working with the new values.\n"
			Switch ON
			exit 0
		fi

		c_loop $1
		;;


	*) exit1;;
esac
