#!/usr/bin/env bash
# Basic shell syntax checker
# Copyright (C) 2018-2019, VR25 @ xda-developers
# License: GPL V3+

echo
cd ${0%/*} 2>/dev/null
for f in $(find ./ -type f -name '*.sh') ./common/acc*; do
  bash -n $f
done
echo
