#!/system/bin/sh
# Advanced Charging Controller
# Copyright (C) 2017-2019, VR25 @ xda-developers
# License: GPL V3+


main() {

  umask 0
  trap exxit EXIT
  set -euo pipefail

  pidFile=/dev/acc/pid
  modPath=/system/etc/acc
  config=/data/media/0/acc/config.txt

  # root check
  echo
  if ! ls /data/data 1>/dev/null 2>&1; then
    echo "(!) Must run as root (su)"
    exit 1
  fi

  if [ ! -f $modPath/module.prop ]; then
    modPath=/sbin/.magisk/img/acc
    if [ -f $modPath/module.prop ]; then
      PATH=/sbin/.magisk/busybox:$PATH
    else
      modPath=/sbin/.core/img/acc
      PATH=/sbin/.core/busybox:$PATH
    fi
  fi

  batt=$(echo /sys/class/power_supply/*attery/capacity | awk '{print $1}' | sed 's|/capacity||')

  if [ ! -d $modPath ]; then
    echo "(!) modPath not found"
    exit 1
  fi

  mkdir -p ${pidFile%/*} ${config%/*}/logs
  [ -f $config ] || install -m 0777 $modPath/default_config.txt $config
  cd /sys/class/power_supply/

  set +u
  case $1 in
    [0-9]*) set_cap $@;;
    -c|--config) shift; edit $config $@;;
    -d|--disable) shift; disable_charging $@;;
    -D|--daemon) shift; daemon $@;;
    -e|--enable) shift; enable_charging $@;;
    -i|--info) sed s/POWER_SUPPLY_// $batt/uevent;;
    -l|--log) shift; edit ${config%/*}/logs/acc-daemon*.log $@;;
    -L)
      if eval $(get_value verbose); then
        tail -F ${config%/*}/logs/acc-daemon*.log
      else
        tail -F ${pidFile%/*}/acc-daemon-*.log
      fi
    ;;
    -r|--readme) shift; edit ${config%/*}/info/README.md $@;;
    -R|--resetstats)
      dumpsys batterystats --reset 1>/dev/null 2>&1 || :
      rm /data/system/batterystats* 2>/dev/null || :
    ;;
    -s|--set) shift; set_values $@;;
    -t|--test)
      shift
      if [ -z "${1-}" ]; then
        test_cctrl_file $(get_value switch)
      else
        test_cctrl_file $@
      fi
    ;;
    -v|--voltage) shift; set_charging_voltage $@;;
    *) help;;
  esac
  set -u
}


daemon() {
  case $1 in
    start)
      if [ -f $pidFile ] && ps | grep $(sed -n 1p $pidFile) 1>/dev/null 2>&1; then
        echo "(i) accd is already running"
      else
        echo "(i) accd started"
        set +x
        accd
      fi
    ;;
    stop)
      if [ -f $pidFile ] && ps | grep $(sed -n 1p $pidFile) 1>/dev/null 2>&1; then
        kill $(cat $pidFile) 2>/dev/null || :
        rm $pidFile
        enable_charging
        echo "(i) accd stopped"
      else
        echo "(i) accd is not running"
      fi
    ;;
    restart)
      if [ -f $pidFile ] && ps | grep $(sed -n 1p $pidFile) 1>/dev/null 2>&1; then
        echo "(i) accd restarted"
      else
        echo "- accd started"
      fi
      set +x
      accd
    ;;
    *)
      if [ -f $pidFile ] && ps | grep $(sed -n 1p $pidFile) 1>/dev/null 2>&1; then
        echo "(i) accd is running"
      else
        echo "(i) accd is not running"
      fi
    ;;
  esac
}


edit() {
  f=$1
  shift
  if [ -n "$1" ]; then
    $@ $f
  else
    vim $f 2>/dev/null || vi $f
  fi
}


help() {
  cat <<HELP
Advanced Charging Controller
Copyright (C) 2017-2019, VR25 @ xda-developers
License: GPL V3+
Version code: $(sed -n 's/versionCode=//p' $modPath/module.prop)

Usage: acc <options> <args>

-c|--config <editor [opts]>   Edit config w/ <editor [opts]> (default: vim|vi)
  e.g., acc -c nano -l

-d|--disable <#%, #s, #m or #h (optional)>   Disable charging or disable charging with <condition>
  e.g., acc -d 70% (do not recharge until capacity drops to 70%), acc -d 1h (do not recharge until 1 hour has passed)

-D|--daemon   Show current acc daemon (accd) state
  i.e., acc -D

-D|--daemon <start|stop|restart>   Manage accd state
  e.g., acc -D restart

-e|--enable <#%, #s, #m or #h (optional)>   Enable charging or enable charging with <condition>
  e.g., acc -e 30m (recharge for 30 minutes)

-i|--info   Show power supply info
  i.e., acc --info

-l|--log <editor [opts]>   Open <acc-daemon-deviceName.log> w/ <editor [opts]> (default: vim|vi)
  e.g., acc -l grep ': ' (show errors only), acc -l cat >/sdcard/acc.log (yes, this also works)

-L   Monitor log

-r|--readme   Open <README.md> w/ <editor [opts]> (default: vim|vi)
  i.e., acc -r

-R|--resetstats   Reset battery stats

-s|--set   Show current config
  i.e., acc --set

-s|--set <var> <value>   Set config parameters
  e.g., acc -s verbose true (enable verbose), acc -s capacity 5,60,80-85 (5: shutdown (default), 60: cool down (default), 80: resume, 85: pause)

-s|--set <resume-stop preset>   Can be 4041|endurance+, 5960|endurance, 7080|default, 8090|lite 9095|travel
  e.g., acc -s endurance+ (a.k.a, "the li-ion sweet spot"; best for GPS navigation and other long operations), acc -s travel (for when you need extra juice), acc -s 7080 (restore default capacity settings (5,60,70-80))

-s|--set <s|switch>   Set a different charging switch from the database
  i.e., acc -s s

-s|--set <s:|switch:>   List available charging switches

-s|--set <s-|switch->   Unset charging switch

-t|--test   Test currently set charging ctrl file
  Return codes: 0 (works), 1 (does not work) or 2 (battery must be charging)

-t|--test <file onValue offValue>   Test custom charging ctrl file
  Return codes: 0 (works), 1 (does not work) or 2 (battery must be charging)

-v|--voltage <xxxx|voltFile:xxxx>   Set charging voltage (mV) on demand (3920-4199mV)
  e.g., acc -v 3920, acc -v /sys/class/power_supply/battery/voltage_max:4100

-v|--voltage   Restore default voltage

-v|--voltage :   List available charging voltage control files

-v|--voltage -   Show current voltage

-v|--voltage :xxxx   Evaluate and set charging voltage control files

-x|--xtrace <other option(s)>   Run under set -x (debugging)

Tips

  Commands can be chained for extended functionality.
    e.g., acc -e 30m && acc -d 6h && acc -e 85 && accd (recharge for 30 minutes, halt charging for 6 hours, recharge to 85% capacity and restart daemon)

  Pause and resume capacities can also be set with acc <pause%> <resume%>.
    e.g., acc 85 80

  Run "djs" to learn how to schedule commands, profiles, and even entire scripts.

Run acc -r to see the full documentation (type "<esc> :q! <enter>" to quit).
HELP
}


set_value() {
  local var=$1
  [ $var = s ] && var=switch || :
  shift
  if grep -q "^$var=" $config; then
    sed -i "s|^$var=[^#]*|$var=$(echo -n $@) |" $config
  elif grep -q "^#$var=" $config; then
    sed -i "s|^#$var=[^#]*|$var=$(echo -n $@) |" $config
  else
    echo "(!) Invalid variable"
    exit 1
  fi
}


set_values() {
  case $1 in
    8090|lite) set_value capacity 5,60,80-90;;
    9095|travel) set_value capacity 5,60,90-95;;
    7080|default) set_value capacity 5,60,70-80;;
    5960|endurance) set_value capacity 5,60,59-60;;
    4041|endurance+) set_value capacity 5,60,40-41;;
    r|reset)
      cp -f $modPath/default_config $config
      chmod 0777 $config
      echo "(i) Config reset"
      return 0
    ;;
    *)
      if [ -n "$1" ]; then
        if [ -z "$2" ] && [[ $1 = s || $1 = switch ]]; then
          set_switch
        elif [ "x$2" = x: ] || [[ $1 = s: || $1 = switch: ]]; then
          list_cctrl_files
        elif [ "x$2" = x- ] || [[ $1 = s- || $1 = switch- ]]; then
          set_value switch
          echo "(i) Charging switch reset"
        else
          set_value $@
        fi
      else
        grep '^[a-z].*=' $config | sed 's/#.*//'
      fi
    ;;
  esac
}


set_switch() {
  local switch="" on="" off="" oIFS=$IFS
  echo "(i) Available charging switches"
  echo "- Choose one and press <enter> to set it"
  echo
  local IFS=$'\n'
  eval 'select switch in $(list_cctrl_files) exit; do
    [ x$switch = xexit ] && exit 0
    IFS=$oIFS
    set_value switch "$switch"
    break
  done'
}


disable_charging() {
  local s="" off=""
  daemon stop | grep -v not && echo
  if get_value switch | grep -q /; then
    s=$(get_value switch | awk '{print $1}')
    off=$(get_value switch | awk '{print $3}')
    if [ -f $s ]; then
      chmod +w $s && echo $off >$s \
        || { echo "(!) [$switch] does not work"
          set_value switch
          exit 1; }
    else
      echo "(!) Invalid charging switch"
      set_value switch
      exit 1
    fi
  else
    switch_loop off
  fi
  set +u
  if [ -n "$1" ]; then
    if echo "$1" | grep -q %; then
      echo "(i) Charging disabled until battery capacity <= $1"
      echo
      until [ $(cat $batt/capacity) -le $(echo $1 | sed 's/%//') ]; do
        sleep $(get_value loopDelay)
      done
      enable_charging
    elif echo "$1" | grep -Eq 's|m|h'; then
      echo "(i) Charging disabled for $1"
      echo
      if echo "$1" | grep -q s; then
        sleep $(echo $1 | sed 's/\s//')
      elif echo "$1" | grep -q m; then
        sleep $(($(echo $1 | sed 's/m//') * 60))
      else
        sleep $(($(echo $1 | sed 's/h//') * 3600))
      fi
      enable_charging
    else
      echo "(i) Charging disabled"
    fi
  else
    echo "(i) Charging disabled"
  fi
}


enable_charging() {
  local s="" on=""
  daemon stop | grep stopped || :
  if get_value switch | grep -q /; then
    s=$(get_value switch | awk '{print $1}')
    on=$(get_value switch | awk '{print $2}')
    if [ -f $s ]; then
      chmod +w $s && echo $on >$s \
        || { echo "(!) [$switch] does not work"
          set_value switch
          exit 1; }
      for l in $(get_value onPlugged); do
        t=$(echo $l | cut -d: -f1)
        v=$(echo $l | cut -d: -f2)
        [ -f $t ] && chmod +w $t && echo $v >$t || :
      done
    else
      echo "(!) Invalid charging switch"
      set_value switch
      exit 1
    fi
  else
    switch_loop on
  fi
  set +u
  if [ -n "$1" ]; then
    if echo "$1" | grep -q %; then
      echo "(i) Charging enabled until battery capacity >= $1"
      echo
      until [ $(cat $batt/capacity) -ge $(echo $1 | sed 's/%//') ]; do
        sleep $(get_value loopDelay)
      done
      disable_charging
    elif echo "$1" | grep -Eq 's|m|h'; then
      echo "(i) Charging enabled for $1"
      echo
      if echo "$1" | grep -q s; then
        sleep $(echo $1 | sed 's/\s//')
      elif echo "$1" | grep -q m; then
        sleep $(($(echo $1 | sed 's/m//') * 60))
      else
        sleep $(($(echo $1 | sed 's/h//') * 3600))
      fi
      disable_charging
    else
      echo "(i) Charging enabled"
    fi
  else
    echo "(i) Charging enabled"
  fi
}


get_value() { sed -n "s:^$1=::p" $config | sed 's/#.*//'; }


exxit() {
  local exitCode=$?
  echo
  exit $exitCode
}


set_cap() {
  local s=$(get_value capacity | cut -d, -f1)
  local c=$(get_value capacity | cut -d, -f2)
  set_value capacity $s,$c,$2-$1
}


switch_loop() {
  local s="" on="" off="" default=""
  while IFS= read -r s; do
    if [ -f $(echo $s | awk '{print $1}') ]; then
      on=$(echo $s | awk '{print $2}')
      off=$(echo $s | awk '{print $3}')
      s=$(echo $s | awk '{print $1}')
      default=$(sed -n 1p $s)
      chmod +w $s && eval "echo \$$1" >$s && sleep 1 || continue
      if { [ $1 = off ] && ! grep -Eiq 'dis|not' $batt/status; } \
        || { [ $1 = on ] && grep -Eiq 'dis|not' $batt/status; }
      then
        echo $default >$s && sleep 1 || :
      else
        break
      fi
    fi
  done <<SWITCHES
$(grep -Ev '#|^$' $modPath/switches.txt)
SWITCHES
}


set_charging_voltage() {

  local value=""
  local setVoltage=false
  local dVolt=${pidFile%/*}/dVolt
  local file=$(echo -n $(get_value voltFile))

  if echo ${1-} | grep -q '^[34]' && [ $1 -ge 3920 ] && [ $1 -le 4199 ] ; then # mV
    setVoltage=true
    value=$1
  elif echo ${1-} | grep -q ':[34]' && [ ${1##*:} -ge 3920 ] && [ ${1##*:} -le 4199 ]; then # override voltFile
    setVoltage=true
    value=${1##*:}
    [[ $1 = */* ]] && file=$(echo ${1%:*}) || vfiles_prompt $value
  elif echo ${1-} | grep -q '^\-$'; then # show current voltage
    if [ -f ${pidFile%/*}/dVolt ]; then
      file=$(awk '{print $1}' ${pidFile%/*}/dVolt)
      cat $file
    else
      echo default
    fi
    return 0
  elif [ -z "${1-}" ]; then # restore default voltage
    if [ -f ${pidFile%/*}/dVolt ]; then
      file=$(awk '{print $1}' ${pidFile%/*}/dVolt)
      value=$(awk '{print $2}' ${pidFile%/*}/dVolt)
      chmod +w $file && echo $value > $file \
      && echo "(i) Default voltage ($(sed -n 1p $file)) was successfully restored."
    else
      echo "(i) Default voltage is already set."
    fi
    return 0
  elif [ x${1-} = x: ]; then
    list_vfiles
    return 0
  else
    echo "(!) Invalid input"
    echo "- Recall that the accepted voltage range is 3920-4199mV."
    return 1
  fi

  if $setVoltage; then
    if [ -f $file ]; then
      if chmod +w $file && sed "s/^..../$value/" $file > $file 2>/dev/null && grep -q "^$value" $file; then
        [ -f $dVolt ] || echo "$file $(sed -n 1p $file)" > $dVolt
        echo "(i) Charging voltage set to $(sed -n 1p $file)."
      else
        echo "(!) Either $(echo -n $file) is not the right file or your kernel does not support this feature."
        return 1
      fi
    else
      echo "(!) No such file, $file"
      return 1
    fi
  fi
}


list_vfiles(){
  grep -E '/constant_charge_voltage$|/voltage_max$' ${config%/*}/logs/acc-power_supply-*.log | sed 's/$/\n/'
}


vfiles_prompt() {
  local file="" success=false
  local PS3="(?) Choice, <enter>: "
  eval 'select file in $(list_vfiles) exit; do
    echo
    [ x$file = xexit ] && exit
    set_charging_voltage $file:$1 && success=true || :
    if $success; then
      echo
      acc -s voltFile $file 1>/dev/null
      echo "(i) voltFile=$file --> config.txt"
      exit 0
    else
      echo
      vfiles_prompt $1
    fi
  done'
}


list_cctrl_files() {
  local file=""
  while IFS= read -r file; do
    [ ! -f $(echo $file | awk '{print $1}') ] || echo $file
  done <<SWITCHES
$(grep -Ev '#|^$' $modPath/switches.txt)
SWITCHES
}


test_cctrl_file() {

  local daemonUp=true
  local on=$(echo "$@" | awk '{print $2}')
  local off=$(echo "$@" | awk '{print $3}')
  local switch=$(echo "$@" | awk '{print $1}')
  [ -z "$switch" ] || local defaultValue=$(sed -n 1p $switch)

  daemon stop | grep stopped 1>/dev/null 2>&1 || daemonUp=false

  if grep -Eiq 'dis|not' $batt/status; then
    echo "(!) Battery must be charging"
    ! $daemonUp || daemon start 1>/dev/null
    return 2
  fi

  if [ -n "${1:-}" ]; then
    chmod +w $switch && echo $off > $switch || :
    sleep 1
    if grep -Eiq 'dis|not' $batt/status; then
      echo "(i) [$switch] works"
      echo $on > $switch
      ! $daemonUp || daemon start 1>/dev/null
      return 0
    else
      echo "(!) [$switch] does not work"
      echo $defaultValue > $switch
      ! $daemonUp || daemon start 1>/dev/null
      return 1
    fi
  else
    disable_charging 1>/dev/null
    if grep -Eiq 'dis|not' $batt/status; then
      echo "(i) Supported device"
      enable_charging 1>/dev/null
      ! $daemonUp || daemon start 1>/dev/null
      return 0
    else
      echo "(!) Unsupported device"
      ! $daemonUp || daemon start 1>/dev/null
      return 1
    fi
  fi
}


# debugging
if [[ "${1:-x}" = "-x" || "${1:-x}" = "--xtrace" ]]; then
  shift
  set -x
fi


main $@
